name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install PDM
      run: pip install pdm

    - name: Install dependencies
      run: pdm install --prod --dev

    - name: Linting
      run: |
        pdm run pylint meine_app tests
        pdm run mypy meine_app tests

    - name: Run tests
      run: pdm run pytest --cov=meine_app tests